sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fulltilt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fulltilt/react-test npm test -- --coverage

  after_success:
    - docker build -t fulltilt/multi-client ./client
    - docker build -t fulltilt/multi-nginx ./nginx
    - docker build -t fulltilt/multi-server ./server
    - docker build -t fulltilt/multi-worker ./worker
    
    # Log into Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Take those images and push them to docker hub
    - docker push fulltilt/multi-client
    - docker push fulltilt/multi-nginx
    - docker push fulltilt/multi-server
    - docker push fulltilt/multi-worker